name: Build STranslate
on:
  push:
分支:
      - main
  pull_request:
分支:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish src/STranslate/STranslate.csproj -c Release -o publish
      - name: Run PowerShell scripts
        shell: pwsh
        run: |
          .\publish.ps1
          .\7z.ps1 -version ${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: STranslate
          path: STranslate_*_win-x64.zip
